### ISSUE TITLE
lack of libcudart.so.7.5

### ISSUE THREAD

**Issue by Lan1991Xu** [smallcorgi/Faster-RCNN_TF#65]
Hi all
I install tensor flow GPU version with CUDA-8.0, cudnn5.0. When I run other my problem, it is seem ok. But I use in Faster-RCNN_TF, it indicate lack of libcudart.so.7.5, then I test row_pooling_op_test.py, it produces the same error. So my question is there any place in roi_pooling need cuda-7.5？I simply add the cuda-7.5/lib64/ to my LD_LIBRARY_PATH, it seems work. But I did not it is really works.

**Comment by soupault** [comment]
@Lan1991Xu you can create a symbolic link like this:
```
sudo su
cd /usr/local/cuda/lib64
ln -s libcudart.so.7.5 libcudart.so.8.0
```

Worked for me.

**Comment by Lan1991Xu** [comment]
@soupault Thanks, it also work. My question is why
Cause this problem? Using 7.5 simply take place of 8.0 it is really woke?

**Comment by soupault** [comment]
@Lan1991Xu I think the version is hard-coded somewhere, although I never found a time to investigate further. 
The suitable version is probably getting infered from the compiler arguments (especially, the list of suported architecures): https://github.com/smallcorgi/Faster-RCNN_TF/blob/25091bb9a5d6e21fe42e9cc4bbe8f952737b35c7/lib/setup.py#L141-L145 .

**Comment by Lan1991Xu** [comment]
Thanks,I guess the problem mabe happen when I use download roi_pooling.so to take place of my roi_pooling.so. because my roi_pooling.so get the error roi_pooling.so: undefined symbol: _Z22ROIPoolBackwardLaucherPKffiiiiiiiS0_PfPKiRKN5Eigen9GpuDeviceE

**Comment by westlee0922** [comment]
> Thanks,I guess the problem mabe happen when I use download roi_pooling.so to take place of my roi_pooling.so. because my roi_pooling.so get the error roi_pooling.so: undefined symbol: _Z22ROIPoolBackwardLaucherPKffiiiiiiiS0_PfPKiRKN5Eigen9GpuDeviceE

soloved or not now?
